/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.hydrology;

import Sirius.navigator.connection.SessionManager;
import Sirius.navigator.exception.ConnectionException;

import Sirius.server.middleware.types.MetaClass;
import Sirius.server.middleware.types.MetaObject;
import Sirius.server.newuser.User;

import org.apache.log4j.Logger;

import org.jdesktop.swingx.decorator.SortOrder;

import org.openide.util.NbBundle;

import java.text.MessageFormat;

import javax.swing.DefaultListModel;

import de.cismet.cids.custom.sudplan.NamedCidsBeanComparator;
import de.cismet.cids.custom.sudplan.NamedCidsBeanListCellRenderer;

import de.cismet.cids.navigator.utils.ClassCacheMultiple;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public final class AssignTimeseriesVisualPanelSelectCalibration extends javax.swing.JPanel {

    //~ Static fields/initializers ---------------------------------------------

    // NOTE: hardcoded id in query sql
    private static final String CALIBRATION_MO_QUERY =
        "SELECT {0}, m.{1} FROM modelinput m JOIN run r ON m.id = r.modelinput WHERE m.model = 4 AND r.started IS NULL"; // NOI18N

    /** LOGGER. */
    private static final transient Logger LOG = Logger.getLogger(AssignTimeseriesVisualPanelSelectCalibration.class);

    //~ Instance fields --------------------------------------------------------

    private final transient AssignTimeseriesWizardPanelSelectCalibration model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    private final transient org.jdesktop.swingx.JXList lstCalibrations = new org.jdesktop.swingx.JXList();
    private final transient javax.swing.JPanel pnlCalibrations = new javax.swing.JPanel();
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form AssignTimeseriesVisualPanelSelectCalibration.
     *
     * @param  model  DOCUMENT ME!
     */
    public AssignTimeseriesVisualPanelSelectCalibration(final AssignTimeseriesWizardPanelSelectCalibration model) {
        this.model = model;
        this.setName("Select Calibration");

        initComponents();

        listInit();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public AssignTimeseriesWizardPanelSelectCalibration getModel() {
        return model;
    }

    /**
     * DOCUMENT ME!
     */
    private void listInit() {
        lstCalibrations.setComparator(new NamedCidsBeanComparator());
        lstCalibrations.setCellRenderer(new NamedCidsBeanListCellRenderer());
    }

    /**
     * DOCUMENT ME!
     */
    void init() {
        bindingGroup.unbind();

        final DefaultListModel listModel = new DefaultListModel();
        lstCalibrations.setModel(listModel);

        final User user = SessionManager.getSession().getUser();
        try {
            final MetaClass mc = ClassCacheMultiple.getMetaClass(user.getDomain(), "modelinput"); // NOI18N
            final String query = MessageFormat.format(CALIBRATION_MO_QUERY, mc.getID(), mc.getPrimaryKey());
            final MetaObject[] mos = SessionManager.getProxy().getMetaObjectByQuery(user, query);

            for (final MetaObject mo : mos) {
                listModel.addElement(mo.getBean());
            }

            lstCalibrations.setSortOrder(SortOrder.ASCENDING);

            if (model.getSelectedCalibration() != null) {
                lstCalibrations.setSelectedValue(model.getSelectedCalibration(), true);
            }
        } catch (final ConnectionException ex) {
            LOG.error("cannot fetch calibration model input meta objects", ex); // NOI18N
            listModel.addElement("Error while searching for calibration model inputs: " + ex);
        }

        bindingGroup.bind();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        pnlCalibrations.setBorder(javax.swing.BorderFactory.createTitledBorder(
                NbBundle.getMessage(
                    AssignTimeseriesVisualPanelSelectCalibration.class,
                    "AssignTimeseriesVisualPanelSelectCalibration.pnlCalibrations.border.title"))); // NOI18N
        pnlCalibrations.setOpaque(false);
        pnlCalibrations.setLayout(new java.awt.GridBagLayout());

        lstCalibrations.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        final org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${model.selectedCalibration}"),
                lstCalibrations,
                org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(lstCalibrations);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        pnlCalibrations.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(pnlCalibrations, gridBagConstraints);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents
}
