/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * TimeSeriesImportFileChoosePanel.java
 *
 * Created on 07.12.2011, 14:37:26
 */
package de.cismet.cids.custom.sudplan.dataImport;

import de.cismet.cids.custom.sudplan.converter.LinzTimeseriesConverter;
import de.cismet.cids.custom.sudplan.converter.TimeSeriesSerializer;
import de.cismet.cids.custom.sudplan.converter.TimeseriesConverter;
import de.cismet.cids.custom.sudplan.converter.WuppertalTimeseriesConverter;

/**
 * DOCUMENT ME!
 *
 * @author   bfriedrich
 * @version  $Revision$, $Date$
 */
public class TimeSeriesConverterChoosePanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient TimeSeriesConverterChoosePanelCtrl ctrl;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboConverterChooser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form TimeSeriesImportFileChoosePanel.
     *
     * @param   ctrl  DOCUMENT ME!
     *
     * @throws  NullPointerException  DOCUMENT ME!
     */
    public TimeSeriesConverterChoosePanel(final TimeSeriesConverterChoosePanelCtrl ctrl) {
        if (ctrl == null) {
            throw new NullPointerException("Given TimeSeriesConverterChoosePanelCtrl instance "
                        + "must not be null"); // NOI18N
        }

        initComponents();

        this.setName(java.util.ResourceBundle.getBundle("de/cismet/cids/custom/sudplan/dataImport/Bundle").getString(
                "TimeSeriesConverterChoosePanel"));
        this.ctrl = ctrl;
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    public void init() {
        // TODO: use lookup
        this.cboConverterChooser.removeAllItems();
        this.cboConverterChooser.addItem(new WuppertalTimeseriesConverter());
        this.cboConverterChooser.addItem(new LinzTimeseriesConverter());
        this.cboConverterChooser.addItem(TimeSeriesSerializer.getInstance());
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public TimeseriesConverter getConverter() {
        return (TimeseriesConverter)this.cboConverterChooser.getSelectedItem();
    }

    /**
     * DOCUMENT ME!
     */

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        cboConverterChooser = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        cboConverterChooser.setMinimumSize(new java.awt.Dimension(300, 27));
        cboConverterChooser.setPreferredSize(new java.awt.Dimension(300, 27));
        jPanel1.add(cboConverterChooser, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
}
