/*
 * Copyright (C) 2011 cismet GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * EtaInputManagerUI.java
 *
 * Created on 07.12.2011, 15:18:55
 */
package de.cismet.cids.custom.sudplan.local.linz;

import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Pascal Dihé
 */
public class EtaInputManagerUI extends javax.swing.JPanel {

    private static final transient Logger LOG = Logger.getLogger(EtaInputManagerUI.class);

    //~ Instance fields --------------------------------------------------------

    private final transient EtaInputManager inputManager;
    
    /** Creates new form EtaInputManagerUI */
    public EtaInputManagerUI(EtaInputManager inputManager) {
        
        // TODO: Better Visualisation (Charts?), Links to CSOs

        this.inputManager = inputManager;
        initComponents();
        init();
    }
    
    protected void init()
    {
        try {
            final EtaInput etaInput = inputManager.getUR();
            DefaultTableModel ctoTableModel = (DefaultTableModel)this.etaTable.getModel();
            for(EtaInput.EtaConfiguration etaConfiguration:etaInput.getEtaConfigurations().values())
            {
                ctoTableModel.addRow(new Object[]{
                etaConfiguration.getName(), etaConfiguration.isEnabled(), 
                etaConfiguration.getSedimentationEfficency()});
            }
        } catch (IOException ex) {
             LOG.error("cannot initialise eta input manager ui", ex); // NOI18N
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etaTableScrollPane = new javax.swing.JScrollPane();
        etaTable = new javax.swing.JTable();

        etaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CSO", "aktiv", "Wirkungsgrad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        etaTableScrollPane.setViewportView(etaTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etaTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etaTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable etaTable;
    private javax.swing.JScrollPane etaTableScrollPane;
    // End of variables declaration//GEN-END:variables
}
