/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.airquality;

import org.openide.util.NbBundle;
import org.openide.util.WeakListeners;

import java.util.Arrays;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public final class AirqualityDownscalingVisualPanelScenarios extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient AirqualityDownscalingWizardPanelScenarios model;
    private final transient ListSelectionListener listL;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescriptionValue;
    private javax.swing.JLabel lblScenarios;
    private javax.swing.JList lstScenarios;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form AirqualityDownscalingVisualPanelScenarios.
     *
     * @param  model  DOCUMENT ME!
     */
    public AirqualityDownscalingVisualPanelScenarios(final AirqualityDownscalingWizardPanelScenarios model) {
        this.model = model;
        this.listL = new ListSelectionListenerImpl();

        // name of the wizard step
        this.setName(NbBundle.getMessage(
                AirqualityDownscalingVisualPanelScenarios.class,
                "AirqualityDownscalingVisualPanelScenarios.this.name")); // NOI18N

        initComponents();

        lstScenarios.addListSelectionListener(WeakListeners.create(ListSelectionListener.class, listL, lstScenarios));
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    String getSelectedScenario() {
        return (String)lstScenarios.getSelectedValue();
    }

    /**
     * DOCUMENT ME!
     */
    void init() {
        final String[] scenarios = model.getScenarios();

        assert scenarios != null : "illegal state, scenarios cannot be null"; // NOI18N

        final DefaultListModel listModel = (DefaultListModel)lstScenarios.getModel();
        listModel.clear();
        Arrays.sort(scenarios);
        for (final String scenario : scenarios) {
            listModel.addElement(scenario);
        }

        if (model.getScenario() == null) {
            lstScenarios.setSelectedIndex(0);
        } else {
            lstScenarios.setSelectedValue(model.getScenario(), true);
        }

        model.fireChangeEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblScenarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstScenarios = new javax.swing.JList();
        lblDescription = new javax.swing.JLabel();
        lblDescriptionValue = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(200, 150));
        setPreferredSize(new java.awt.Dimension(450, 300));
        setLayout(new java.awt.GridBagLayout());

        lblScenarios.setText(NbBundle.getMessage(
                AirqualityDownscalingVisualPanelScenarios.class,
                "AirqualityDownscalingVisualPanelScenarios.lblScenarios.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        add(lblScenarios, gridBagConstraints);

        lstScenarios.setModel(new DefaultListModel());
        lstScenarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstScenarios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 337;
        gridBagConstraints.ipady = 213;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 20, 20, 20);
        add(jScrollPane1, gridBagConstraints);

        lblDescription.setText(NbBundle.getMessage(
                AirqualityDownscalingVisualPanelScenarios.class,
                "AirqualityDownscalingVisualPanelScenarios.lblDescription.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        add(lblDescription, gridBagConstraints);

        lblDescriptionValue.setText(NbBundle.getMessage(
                AirqualityDownscalingVisualPanelScenarios.class,
                "AirqualityDownscalingVisualPanelScenarios.lblDescriptionValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 20);
        add(lblDescriptionValue, gridBagConstraints);
    }                                                                                   // </editor-fold>//GEN-END:initComponents

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class ListSelectionListenerImpl implements ListSelectionListener {

        //~ Methods ------------------------------------------------------------

        @Override
        public void valueChanged(final ListSelectionEvent e) {
            model.fireChangeEvent();

            // FIXME: hardcoded description
            if ("ECHAM5 A1B 3 RCP 4.5".equals(lstScenarios.getSelectedValue())) {
                lblDescriptionValue.setText(
                    "<html>"
                            + "This data was calculated using the ECHAM 5 global climate model operated by the Max-Planck-"
                            + "Institut für Meterologie, Hamburg, Germany. The A1B greenhouse gas climate scenario in "
                            + "variation 3 was utilised and European tracer emissions tuned to a net radiative forcing of "
                            + "4.5 W/m² at stabilization after year 2100."
                            + "</html>");
            } else if ("HADLEY A1B RCP 4.5".equals(lstScenarios.getSelectedValue())) {
                lblDescriptionValue.setText(
                    "<html>"
                            + "This data was calculated using the HADLEY global climate model operated by Hadley Centre, "
                            + "Bracknell, UK. The A1B greenhouse gas climate scenario was utilised and European tracer "
                            + "emissions tuned to a net radiative forcing of 4.5 W/m² at stabilization after year 2100."
                            + "</html>");
            } else {
                lblDescriptionValue.setText(null);
            }
        }
    }
}
