/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.local.wupp;

import Sirius.navigator.connection.SessionManager;
import Sirius.navigator.exception.ConnectionException;

import Sirius.server.localserver.attribute.ClassAttribute;
import Sirius.server.middleware.types.MetaClass;
import Sirius.server.middleware.types.MetaObject;

import org.apache.log4j.Logger;

import org.openide.util.NbBundle;
import org.openide.util.WeakListeners;

import java.awt.Component;

import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import de.cismet.cids.dynamics.CidsBean;

import de.cismet.cids.navigator.utils.ClassCacheMultiple;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class RunGeoCPMVisualPanelTimeseries extends javax.swing.JPanel {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient Logger LOG = Logger.getLogger(RunGeoCPMVisualPanelInput.class);

    //~ Instance fields --------------------------------------------------------

    private final transient RunGeoCPMWizardPanelTimerseries model;

    private final transient ListSelectionListener listL;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlsAvailableTimeseries;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form RunGeoCPMVisualPanelInput.
     *
     * @param   model  DOCUMENT ME!
     *
     * @throws  WizardInitialisationException  DOCUMENT ME!
     */
    public RunGeoCPMVisualPanelTimeseries(final RunGeoCPMWizardPanelTimerseries model)
            throws WizardInitialisationException {
        this.model = model;
        listL = new SelectionListener();

        initComponents();

        // TODO: create default bindable jlist
        initTimeseriesList();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @throws  WizardInitialisationException  DOCUMENT ME!
     */
    private void initTimeseriesList() throws WizardInitialisationException {
        final String domain = SessionManager.getSession().getUser().getDomain();
        final MetaClass mc = ClassCacheMultiple.getMetaClass(domain, RunGeoCPMWizardAction.TABLENAME_TIMESERIES);

        if (mc == null) {
            throw new WizardInitialisationException("cannot fetch timeseries metaclass"); // NOI18N
        }

        final StringBuilder sb = new StringBuilder();

        sb.append("SELECT ").append(mc.getID()).append(',').append(mc.getPrimaryKey()); // NOI18N
        sb.append(" FROM ").append(mc.getTableName());                                  // NOI18N

        final ClassAttribute ca = mc.getClassAttribute("sortingColumn"); // NOI18N
        if (ca != null) {
            sb.append(" ORDER BY ").append(ca.getValue());               // NOI18N
        }

        final MetaObject[] metaObjects;
        try {
            metaObjects = SessionManager.getProxy().getMetaObjectByQuery(sb.toString(), 0);
        } catch (final ConnectionException ex) {
            final String message = "cannot get timeseries meta objects from database"; // NOI18N
            LOG.error(message, ex);
            throw new WizardInitialisationException(message, ex);
        }

        final DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < metaObjects.length; ++i) {
            dlm.addElement(metaObjects[i].getBean());
        }

        jlsAvailableTimeseries.setModel(dlm);
        jlsAvailableTimeseries.setCellRenderer(new NameRenderer());
        jlsAvailableTimeseries.addListSelectionListener(WeakListeners.create(
                ListSelectionListener.class,
                listL,
                jlsAvailableTimeseries));
    }

    /**
     * DOCUMENT ME!
     */
    void init() {
        final DefaultListModel dlm = (DefaultListModel)jlsAvailableTimeseries.getModel();
        if (dlm.contains(model.getTimeseries())) {
            jlsAvailableTimeseries.setSelectedValue(model.getTimeseries(), true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        final java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jlsAvailableTimeseries = new javax.swing.JList();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jlsAvailableTimeseries.setBorder(javax.swing.BorderFactory.createTitledBorder(
                NbBundle.getMessage(
                    RunGeoCPMVisualPanelTimeseries.class,
                    "RunGeoCPMVisualPanelTimeseries.jlsAvailableTimeseries.border.title"))); // NOI18N
        jlsAvailableTimeseries.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlsAvailableTimeseries);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane1, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class SelectionListener implements ListSelectionListener {

        //~ Methods ------------------------------------------------------------

        @Override
        public void valueChanged(final ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                if (e.getFirstIndex() == e.getLastIndex()) {
                    model.setTimeseries((CidsBean)jlsAvailableTimeseries.getSelectedValue());
                }
            }
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private static final class NameRenderer extends DefaultListCellRenderer {

        //~ Methods ------------------------------------------------------------

        @Override
        public Component getListCellRendererComponent(final JList list,
                final Object value,
                final int index,
                final boolean isSelected,
                final boolean cellHasFocus) {
            final Component comp = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if ((comp instanceof JLabel) && (value instanceof CidsBean)) {
                final JLabel label = (JLabel)comp;
                final CidsBean obj = (CidsBean)value;
                final String name = (String)obj.getProperty("name");           // NOI18N
                final boolean forecast = (Boolean)obj.getProperty("forecast"); // NOI18N

                if (forecast) {
                    label.setText(name + " (forecast)");
                } else {
                    label.setText(name);
                }
            }

            return comp;
        }
    }
}
