/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.rainfall;

import Sirius.navigator.connection.SessionManager;
import Sirius.navigator.ui.ComponentRegistry;

import Sirius.server.middleware.types.MetaClass;

import org.openide.util.NbBundle;
import org.openide.util.WeakListeners;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import de.cismet.cids.navigator.utils.ClassCacheMultiple;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class RainfallDownscalingInputManagerUI extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient ActionListener openRFObjL;
    private final transient ChangeListener freqAdjustL;

    private final transient RainfallDownscalingInput model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JCheckBox chkFreqAdjust = new javax.swing.JCheckBox();
    private final transient org.jdesktop.swingx.JXHyperlink hypRainfallObject = new org.jdesktop.swingx.JXHyperlink();
    private final transient javax.swing.JLabel lblCreated = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblCreatedBy = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblCreatedByValue = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblCreatedValue = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblFreqAdjust = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblName = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblNameValue = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblRainfallObject = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblScenario = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblScenarioValue = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblTargetYear = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblTargetYearValue = new javax.swing.JLabel();
    private final transient javax.swing.JPanel pnlFiller = new javax.swing.JPanel();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form RainfallDownscalingInputManagerUI.
     *
     * @param  model  DOCUMENT ME!
     */
    public RainfallDownscalingInputManagerUI(final RainfallDownscalingInput model) {
        this.openRFObjL = new OpenRainfallObjectActionListener();
        this.freqAdjustL = new PreventChangeListener();
        this.model = model;

        initComponents();

        init();

        hypRainfallObject.addActionListener(WeakListeners.create(ActionListener.class, openRFObjL, hypRainfallObject));
        chkFreqAdjust.addChangeListener(WeakListeners.change(freqAdjustL, chkFreqAdjust));
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    private void init() {
        lblNameValue.setText(model.getName());
        lblCreatedValue.setText(model.getCreated().toString());
        lblCreatedByValue.setText(model.getCreatedBy());
        lblScenarioValue.setText(model.getScenario());
        lblTargetYearValue.setText(model.getTargetYear().toString());
        hypRainfallObject.setText(model.getRainfallObjectName());
        chkFreqAdjust.setSelected(model.isFrequencyAdjustment());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblName.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblName, gridBagConstraints);

        lblCreated.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblCreated.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblCreated, gridBagConstraints);

        lblCreatedValue.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblCreatedValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblCreatedValue, gridBagConstraints);

        lblNameValue.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblNameValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblNameValue, gridBagConstraints);

        lblCreatedBy.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblCreatedBy.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblCreatedBy, gridBagConstraints);

        lblCreatedByValue.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblCreatedByValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblCreatedByValue, gridBagConstraints);

        lblScenario.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblScenario.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblScenario, gridBagConstraints);

        lblScenarioValue.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblScenarioValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblScenarioValue, gridBagConstraints);

        lblTargetYear.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblTargetYear.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblTargetYear, gridBagConstraints);

        lblTargetYearValue.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblTargetYearValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblTargetYearValue, gridBagConstraints);

        lblRainfallObject.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblRainfallObject.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblRainfallObject, gridBagConstraints);

        pnlFiller.setOpaque(false);

        final org.jdesktop.layout.GroupLayout pnlFillerLayout = new org.jdesktop.layout.GroupLayout(pnlFiller);
        pnlFiller.setLayout(pnlFillerLayout);
        pnlFillerLayout.setHorizontalGroup(
            pnlFillerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 0, Short.MAX_VALUE));
        pnlFillerLayout.setVerticalGroup(
            pnlFillerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 0, Short.MAX_VALUE));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        add(pnlFiller, gridBagConstraints);

        hypRainfallObject.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.hypRainfallObject.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(hypRainfallObject, gridBagConstraints);

        lblFreqAdjust.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.lblFreqAdjust.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(lblFreqAdjust, gridBagConstraints);

        chkFreqAdjust.setText(NbBundle.getMessage(
                RainfallDownscalingInputManagerUI.class,
                "RainfallDownscalingInputManagerUI.chkFreqAdjust.text")); // NOI18N
        chkFreqAdjust.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(chkFreqAdjust, gridBagConstraints);
    }                                                                     // </editor-fold>//GEN-END:initComponents

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class PreventChangeListener implements ChangeListener {

        //~ Methods ------------------------------------------------------------

        @Override
        public void stateChanged(final ChangeEvent e) {
            chkFreqAdjust.setSelected(model.isFrequencyAdjustment());
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class OpenRainfallObjectActionListener implements ActionListener {

        //~ Methods ------------------------------------------------------------

        @Override
        public void actionPerformed(final ActionEvent e) {
            final MetaClass metaclass = ClassCacheMultiple.getMetaClass(
                    SessionManager.getSession().getUser().getDomain(),
                    model.getRainfallObjectTableName());

            assert metaclass != null : "rainfall object metaclass not present"; // NOI18N

            ComponentRegistry.getRegistry()
                    .getDescriptionPane()
                    .gotoMetaObject(metaclass, model.getRainfallObjectId(), ""); // NOI18N
        }
    }
}
