/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.objectrenderer.sudplan;

import org.apache.log4j.Logger;

import org.openide.util.NbBundle;

import java.awt.BorderLayout;

import java.net.MalformedURLException;

import javax.swing.SwingUtilities;

import de.cismet.cids.custom.sudplan.AbstractCidsBeanRenderer;
import de.cismet.cids.custom.sudplan.SMSUtils;
import de.cismet.cids.custom.sudplan.TimeseriesChartPanel;
import de.cismet.cids.custom.sudplan.TimeseriesRetrieverConfig;
import de.cismet.cids.custom.sudplan.converter.TimeseriesConverter;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class TimeseriesRenderer extends AbstractCidsBeanRenderer {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient Logger LOG = Logger.getLogger(TimeseriesRenderer.class);

    //~ Instance fields --------------------------------------------------------

    private transient TimeseriesChartPanel panel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkforecast;
    private javax.swing.JPanel pnlFiller;
    private javax.swing.JPanel pnlNorth;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form TimeseriesRenderer.
     */
    public TimeseriesRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @throws  RuntimeException  MalformedURLException DOCUMENT ME!
     */
    private void setTimeSeriesPanel() {
        try {
            final String uri = (String)cidsBean.getProperty("uri"); // NOI18N
            final TimeseriesConverter converter = SMSUtils.loadConverter(cidsBean);

            final TimeseriesRetrieverConfig config = TimeseriesRetrieverConfig.fromUrl(uri);

            final TimeseriesRetrieverConfig tsrConfig = config;

            SwingUtilities.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        if (panel != null) {
                            TimeseriesRenderer.this.remove(panel);
                        }

                        TimeseriesRenderer.this.panel = new TimeseriesChartPanel(tsrConfig, converter, true);
                        TimeseriesRenderer.this.add(TimeseriesRenderer.this.panel, BorderLayout.CENTER);

                        TimeseriesRenderer.this.invalidate();
                        TimeseriesRenderer.this.validate();
                    }
                });
        } catch (final MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    protected void init() {
        bindingGroup.unbind();
        bindingGroup.bind();

//        try {
//            final String uri = (String) cidsBean.getProperty("uri"); // NOI18N
//            final TimeseriesRetrieverConfig config = TimeseriesRetrieverConfig.fromUrl(uri);

//            final TimeSeriesExportWizardAction action = (TimeSeriesExportWizardAction)btnExport.getAction();
//            action.setTimeseriesRetrieverConfig(config);
//            btnExport.setEnabled(true);

        this.setTimeSeriesPanel();
//        } catch (final MalformedURLException ex) {
//            btnExport.setEnabled(false);

//            final String message = "cidsbean contains invalid uri"; // NOI18N
//            LOG.error(message, ex);
//            throw new IllegalStateException(message, ex);
//        }
    }

    @Override
    public void dispose() {
        if (panel != null) {
            panel.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlNorth = new javax.swing.JPanel();
        chkforecast = new javax.swing.JCheckBox();
        pnlFiller = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        pnlNorth.setOpaque(false);
        pnlNorth.setLayout(new java.awt.GridBagLayout());

        chkforecast.setText(NbBundle.getMessage(TimeseriesRenderer.class, "TimeseriesRenderer.chkforecast.text")); // NOI18N
        chkforecast.setContentAreaFilled(false);

        final org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.forecast}"),
                chkforecast,
                org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        pnlNorth.add(chkforecast, gridBagConstraints);

        pnlFiller.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlNorth.add(pnlFiller, gridBagConstraints);

        add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents
}
